// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(sanct_swiftFFI)
import sanct_swiftFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_sanct_swift_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_sanct_swift_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


public struct IdentityKeys {
    public var x25519Public: Data
    public var mlkem768Public: Data
    public var encryptedPrivateBundle: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(x25519Public: Data, mlkem768Public: Data, encryptedPrivateBundle: Data) {
        self.x25519Public = x25519Public
        self.mlkem768Public = mlkem768Public
        self.encryptedPrivateBundle = encryptedPrivateBundle
    }
}



extension IdentityKeys: Equatable, Hashable {
    public static func ==(lhs: IdentityKeys, rhs: IdentityKeys) -> Bool {
        if lhs.x25519Public != rhs.x25519Public {
            return false
        }
        if lhs.mlkem768Public != rhs.mlkem768Public {
            return false
        }
        if lhs.encryptedPrivateBundle != rhs.encryptedPrivateBundle {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(x25519Public)
        hasher.combine(mlkem768Public)
        hasher.combine(encryptedPrivateBundle)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIdentityKeys: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IdentityKeys {
        return
            try IdentityKeys(
                x25519Public: FfiConverterData.read(from: &buf), 
                mlkem768Public: FfiConverterData.read(from: &buf), 
                encryptedPrivateBundle: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: IdentityKeys, into buf: inout [UInt8]) {
        FfiConverterData.write(value.x25519Public, into: &buf)
        FfiConverterData.write(value.mlkem768Public, into: &buf)
        FfiConverterData.write(value.encryptedPrivateBundle, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentityKeys_lift(_ buf: RustBuffer) throws -> IdentityKeys {
    return try FfiConverterTypeIdentityKeys.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentityKeys_lower(_ value: IdentityKeys) -> RustBuffer {
    return FfiConverterTypeIdentityKeys.lower(value)
}


public struct PgpDecryptResult {
    public var plaintext: Data
    public var fingerprintUsed: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(plaintext: Data, fingerprintUsed: String) {
        self.plaintext = plaintext
        self.fingerprintUsed = fingerprintUsed
    }
}



extension PgpDecryptResult: Equatable, Hashable {
    public static func ==(lhs: PgpDecryptResult, rhs: PgpDecryptResult) -> Bool {
        if lhs.plaintext != rhs.plaintext {
            return false
        }
        if lhs.fingerprintUsed != rhs.fingerprintUsed {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(plaintext)
        hasher.combine(fingerprintUsed)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePgpDecryptResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PgpDecryptResult {
        return
            try PgpDecryptResult(
                plaintext: FfiConverterData.read(from: &buf), 
                fingerprintUsed: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: PgpDecryptResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.plaintext, into: &buf)
        FfiConverterString.write(value.fingerprintUsed, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePgpDecryptResult_lift(_ buf: RustBuffer) throws -> PgpDecryptResult {
    return try FfiConverterTypePgpDecryptResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePgpDecryptResult_lower(_ value: PgpDecryptResult) -> RustBuffer {
    return FfiConverterTypePgpDecryptResult.lower(value)
}


public struct PgpGeneratedKey {
    public var armoredPublic: String
    public var armoredSecret: String
    public var fingerprint: String
    public var primaryUid: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(armoredPublic: String, armoredSecret: String, fingerprint: String, primaryUid: String) {
        self.armoredPublic = armoredPublic
        self.armoredSecret = armoredSecret
        self.fingerprint = fingerprint
        self.primaryUid = primaryUid
    }
}



extension PgpGeneratedKey: Equatable, Hashable {
    public static func ==(lhs: PgpGeneratedKey, rhs: PgpGeneratedKey) -> Bool {
        if lhs.armoredPublic != rhs.armoredPublic {
            return false
        }
        if lhs.armoredSecret != rhs.armoredSecret {
            return false
        }
        if lhs.fingerprint != rhs.fingerprint {
            return false
        }
        if lhs.primaryUid != rhs.primaryUid {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(armoredPublic)
        hasher.combine(armoredSecret)
        hasher.combine(fingerprint)
        hasher.combine(primaryUid)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePgpGeneratedKey: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PgpGeneratedKey {
        return
            try PgpGeneratedKey(
                armoredPublic: FfiConverterString.read(from: &buf), 
                armoredSecret: FfiConverterString.read(from: &buf), 
                fingerprint: FfiConverterString.read(from: &buf), 
                primaryUid: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: PgpGeneratedKey, into buf: inout [UInt8]) {
        FfiConverterString.write(value.armoredPublic, into: &buf)
        FfiConverterString.write(value.armoredSecret, into: &buf)
        FfiConverterString.write(value.fingerprint, into: &buf)
        FfiConverterString.write(value.primaryUid, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePgpGeneratedKey_lift(_ buf: RustBuffer) throws -> PgpGeneratedKey {
    return try FfiConverterTypePgpGeneratedKey.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePgpGeneratedKey_lower(_ value: PgpGeneratedKey) -> RustBuffer {
    return FfiConverterTypePgpGeneratedKey.lower(value)
}


public struct PgpImportedKey {
    public var armoredSecret: String
    public var armoredPublic: String
    public var fingerprint: String
    public var uids: [String]
    public var createdAtUnix: Int64
    public var expiresAtUnix: Int64?
    public var isExpired: Bool
    public var isRevoked: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(armoredSecret: String, armoredPublic: String, fingerprint: String, uids: [String], createdAtUnix: Int64, expiresAtUnix: Int64?, isExpired: Bool, isRevoked: Bool) {
        self.armoredSecret = armoredSecret
        self.armoredPublic = armoredPublic
        self.fingerprint = fingerprint
        self.uids = uids
        self.createdAtUnix = createdAtUnix
        self.expiresAtUnix = expiresAtUnix
        self.isExpired = isExpired
        self.isRevoked = isRevoked
    }
}



extension PgpImportedKey: Equatable, Hashable {
    public static func ==(lhs: PgpImportedKey, rhs: PgpImportedKey) -> Bool {
        if lhs.armoredSecret != rhs.armoredSecret {
            return false
        }
        if lhs.armoredPublic != rhs.armoredPublic {
            return false
        }
        if lhs.fingerprint != rhs.fingerprint {
            return false
        }
        if lhs.uids != rhs.uids {
            return false
        }
        if lhs.createdAtUnix != rhs.createdAtUnix {
            return false
        }
        if lhs.expiresAtUnix != rhs.expiresAtUnix {
            return false
        }
        if lhs.isExpired != rhs.isExpired {
            return false
        }
        if lhs.isRevoked != rhs.isRevoked {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(armoredSecret)
        hasher.combine(armoredPublic)
        hasher.combine(fingerprint)
        hasher.combine(uids)
        hasher.combine(createdAtUnix)
        hasher.combine(expiresAtUnix)
        hasher.combine(isExpired)
        hasher.combine(isRevoked)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePgpImportedKey: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PgpImportedKey {
        return
            try PgpImportedKey(
                armoredSecret: FfiConverterString.read(from: &buf), 
                armoredPublic: FfiConverterString.read(from: &buf), 
                fingerprint: FfiConverterString.read(from: &buf), 
                uids: FfiConverterSequenceString.read(from: &buf), 
                createdAtUnix: FfiConverterInt64.read(from: &buf), 
                expiresAtUnix: FfiConverterOptionInt64.read(from: &buf), 
                isExpired: FfiConverterBool.read(from: &buf), 
                isRevoked: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: PgpImportedKey, into buf: inout [UInt8]) {
        FfiConverterString.write(value.armoredSecret, into: &buf)
        FfiConverterString.write(value.armoredPublic, into: &buf)
        FfiConverterString.write(value.fingerprint, into: &buf)
        FfiConverterSequenceString.write(value.uids, into: &buf)
        FfiConverterInt64.write(value.createdAtUnix, into: &buf)
        FfiConverterOptionInt64.write(value.expiresAtUnix, into: &buf)
        FfiConverterBool.write(value.isExpired, into: &buf)
        FfiConverterBool.write(value.isRevoked, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePgpImportedKey_lift(_ buf: RustBuffer) throws -> PgpImportedKey {
    return try FfiConverterTypePgpImportedKey.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePgpImportedKey_lower(_ value: PgpImportedKey) -> RustBuffer {
    return FfiConverterTypePgpImportedKey.lower(value)
}


public struct PgpPublicKeyInfo {
    public var fingerprint: String
    public var uids: [String]
    public var createdAtUnix: Int64
    public var expiresAtUnix: Int64?
    public var isExpired: Bool
    public var isRevoked: Bool
    public var canEncrypt: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(fingerprint: String, uids: [String], createdAtUnix: Int64, expiresAtUnix: Int64?, isExpired: Bool, isRevoked: Bool, canEncrypt: Bool) {
        self.fingerprint = fingerprint
        self.uids = uids
        self.createdAtUnix = createdAtUnix
        self.expiresAtUnix = expiresAtUnix
        self.isExpired = isExpired
        self.isRevoked = isRevoked
        self.canEncrypt = canEncrypt
    }
}



extension PgpPublicKeyInfo: Equatable, Hashable {
    public static func ==(lhs: PgpPublicKeyInfo, rhs: PgpPublicKeyInfo) -> Bool {
        if lhs.fingerprint != rhs.fingerprint {
            return false
        }
        if lhs.uids != rhs.uids {
            return false
        }
        if lhs.createdAtUnix != rhs.createdAtUnix {
            return false
        }
        if lhs.expiresAtUnix != rhs.expiresAtUnix {
            return false
        }
        if lhs.isExpired != rhs.isExpired {
            return false
        }
        if lhs.isRevoked != rhs.isRevoked {
            return false
        }
        if lhs.canEncrypt != rhs.canEncrypt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(fingerprint)
        hasher.combine(uids)
        hasher.combine(createdAtUnix)
        hasher.combine(expiresAtUnix)
        hasher.combine(isExpired)
        hasher.combine(isRevoked)
        hasher.combine(canEncrypt)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePgpPublicKeyInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PgpPublicKeyInfo {
        return
            try PgpPublicKeyInfo(
                fingerprint: FfiConverterString.read(from: &buf), 
                uids: FfiConverterSequenceString.read(from: &buf), 
                createdAtUnix: FfiConverterInt64.read(from: &buf), 
                expiresAtUnix: FfiConverterOptionInt64.read(from: &buf), 
                isExpired: FfiConverterBool.read(from: &buf), 
                isRevoked: FfiConverterBool.read(from: &buf), 
                canEncrypt: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: PgpPublicKeyInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.fingerprint, into: &buf)
        FfiConverterSequenceString.write(value.uids, into: &buf)
        FfiConverterInt64.write(value.createdAtUnix, into: &buf)
        FfiConverterOptionInt64.write(value.expiresAtUnix, into: &buf)
        FfiConverterBool.write(value.isExpired, into: &buf)
        FfiConverterBool.write(value.isRevoked, into: &buf)
        FfiConverterBool.write(value.canEncrypt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePgpPublicKeyInfo_lift(_ buf: RustBuffer) throws -> PgpPublicKeyInfo {
    return try FfiConverterTypePgpPublicKeyInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePgpPublicKeyInfo_lower(_ value: PgpPublicKeyInfo) -> RustBuffer {
    return FfiConverterTypePgpPublicKeyInfo.lower(value)
}


public struct PrivateKeys {
    public var x25519Secret: Data
    public var mlkem768Secret: Data
    public var threadingKey: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(x25519Secret: Data, mlkem768Secret: Data, threadingKey: Data) {
        self.x25519Secret = x25519Secret
        self.mlkem768Secret = mlkem768Secret
        self.threadingKey = threadingKey
    }
}



extension PrivateKeys: Equatable, Hashable {
    public static func ==(lhs: PrivateKeys, rhs: PrivateKeys) -> Bool {
        if lhs.x25519Secret != rhs.x25519Secret {
            return false
        }
        if lhs.mlkem768Secret != rhs.mlkem768Secret {
            return false
        }
        if lhs.threadingKey != rhs.threadingKey {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(x25519Secret)
        hasher.combine(mlkem768Secret)
        hasher.combine(threadingKey)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePrivateKeys: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PrivateKeys {
        return
            try PrivateKeys(
                x25519Secret: FfiConverterData.read(from: &buf), 
                mlkem768Secret: FfiConverterData.read(from: &buf), 
                threadingKey: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: PrivateKeys, into buf: inout [UInt8]) {
        FfiConverterData.write(value.x25519Secret, into: &buf)
        FfiConverterData.write(value.mlkem768Secret, into: &buf)
        FfiConverterData.write(value.threadingKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrivateKeys_lift(_ buf: RustBuffer) throws -> PrivateKeys {
    return try FfiConverterTypePrivateKeys.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrivateKeys_lower(_ value: PrivateKeys) -> RustBuffer {
    return FfiConverterTypePrivateKeys.lower(value)
}


public struct RecoveryResult {
    public var phrase: String
    public var recoveryKey: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(phrase: String, recoveryKey: Data) {
        self.phrase = phrase
        self.recoveryKey = recoveryKey
    }
}



extension RecoveryResult: Equatable, Hashable {
    public static func ==(lhs: RecoveryResult, rhs: RecoveryResult) -> Bool {
        if lhs.phrase != rhs.phrase {
            return false
        }
        if lhs.recoveryKey != rhs.recoveryKey {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(phrase)
        hasher.combine(recoveryKey)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRecoveryResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RecoveryResult {
        return
            try RecoveryResult(
                phrase: FfiConverterString.read(from: &buf), 
                recoveryKey: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: RecoveryResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.phrase, into: &buf)
        FfiConverterData.write(value.recoveryKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecoveryResult_lift(_ buf: RustBuffer) throws -> RecoveryResult {
    return try FfiConverterTypeRecoveryResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecoveryResult_lower(_ value: RecoveryResult) -> RustBuffer {
    return FfiConverterTypeRecoveryResult.lower(value)
}


public enum SanctCryptoError {

    
    
    case Crypto(message: String)
    
    case Pgp(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSanctCryptoError: FfiConverterRustBuffer {
    typealias SwiftType = SanctCryptoError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SanctCryptoError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Crypto(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Pgp(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SanctCryptoError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Crypto(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Pgp(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))

        
        }
    }
}


extension SanctCryptoError: Equatable, Hashable {}

extension SanctCryptoError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceData: FfiConverterRustBuffer {
    typealias SwiftType = [Data]

    public static func write(_ value: [Data], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterData.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Data] {
        let len: Int32 = try readInt(&buf)
        var seq = [Data]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterData.read(from: &buf))
        }
        return seq
    }
}
public func computeSubjectHash(threadingKey: Data, subject: String) -> Data {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_sanct_swift_fn_func_compute_subject_hash(
        FfiConverterData.lower(threadingKey),
        FfiConverterString.lower(subject),$0
    )
})
}
public func decryptBundleWithRecovery(recoveryKey: Data, recoveryEncryptedBundle: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_decrypt_bundle_with_recovery(
        FfiConverterData.lower(recoveryKey),
        FfiConverterData.lower(recoveryEncryptedBundle),$0
    )
})
}
public func decryptMessage(x25519Private: Data, mlkemPrivate: Data, sealedBytes: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_decrypt_message(
        FfiConverterData.lower(x25519Private),
        FfiConverterData.lower(mlkemPrivate),
        FfiConverterData.lower(sealedBytes),$0
    )
})
}
public func decryptMetadata(key: Data, ciphertext: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_decrypt_metadata(
        FfiConverterData.lower(key),
        FfiConverterData.lower(ciphertext),$0
    )
})
}
public func decryptPrivateKeys(masterKey: Data, encryptedBundle: Data)throws  -> PrivateKeys {
    return try  FfiConverterTypePrivateKeys.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_decrypt_private_keys(
        FfiConverterData.lower(masterKey),
        FfiConverterData.lower(encryptedBundle),$0
    )
})
}
public func deriveMasterKey(password: String, salt: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_derive_master_key(
        FfiConverterString.lower(password),
        FfiConverterData.lower(salt),$0
    )
})
}
public func encryptBundleForRecovery(recoveryKey: Data, privateBundlePlaintext: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_encrypt_bundle_for_recovery(
        FfiConverterData.lower(recoveryKey),
        FfiConverterData.lower(privateBundlePlaintext),$0
    )
})
}
public func encryptDraft(ownX25519Pub: Data, ownMlkemPub: Data, plaintext: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_encrypt_draft(
        FfiConverterData.lower(ownX25519Pub),
        FfiConverterData.lower(ownMlkemPub),
        FfiConverterData.lower(plaintext),$0
    )
})
}
public func encryptMessage(recipientX25519Pub: Data, recipientMlkemPub: Data, plaintext: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_encrypt_message(
        FfiConverterData.lower(recipientX25519Pub),
        FfiConverterData.lower(recipientMlkemPub),
        FfiConverterData.lower(plaintext),$0
    )
})
}
public func encryptMetadata(key: Data, plaintext: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_encrypt_metadata(
        FfiConverterData.lower(key),
        FfiConverterData.lower(plaintext),$0
    )
})
}
public func generateIdentityKeys(masterKey: Data)throws  -> IdentityKeys {
    return try  FfiConverterTypeIdentityKeys.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_generate_identity_keys(
        FfiConverterData.lower(masterKey),$0
    )
})
}
public func generateRecoveryPhrase() -> RecoveryResult {
    return try!  FfiConverterTypeRecoveryResult.lift(try! rustCall() {
    uniffi_sanct_swift_fn_func_generate_recovery_phrase($0
    )
})
}
public func generateSalt() -> Data {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_sanct_swift_fn_func_generate_salt($0
    )
})
}
public func hashRecoveryKey(recoveryKey: Data) -> Data {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_sanct_swift_fn_func_hash_recovery_key(
        FfiConverterData.lower(recoveryKey),$0
    )
})
}
public func pgpDecryptMessage(armoredSecrets: [Data], armoredCiphertext: Data)throws  -> PgpDecryptResult {
    return try  FfiConverterTypePgpDecryptResult.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_pgp_decrypt_message(
        FfiConverterSequenceData.lower(armoredSecrets),
        FfiConverterData.lower(armoredCiphertext),$0
    )
})
}
public func pgpEncryptToRecipients(armoredPublics: [Data], plaintext: Data)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_pgp_encrypt_to_recipients(
        FfiConverterSequenceData.lower(armoredPublics),
        FfiConverterData.lower(plaintext),$0
    )
})
}
public func pgpExportKey(unprotectedArmored: Data, passphrase: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_pgp_export_key(
        FfiConverterData.lower(unprotectedArmored),
        FfiConverterString.lower(passphrase),$0
    )
})
}
public func pgpGenerateKey(name: String, email: String)throws  -> PgpGeneratedKey {
    return try  FfiConverterTypePgpGeneratedKey.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_pgp_generate_key(
        FfiConverterString.lower(name),
        FfiConverterString.lower(email),$0
    )
})
}
public func pgpImportKey(input: Data, passphrase: String?)throws  -> PgpImportedKey {
    return try  FfiConverterTypePgpImportedKey.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_pgp_import_key(
        FfiConverterData.lower(input),
        FfiConverterOptionString.lower(passphrase),$0
    )
})
}
public func pgpKeyInfo(armoredPublic: Data)throws  -> PgpPublicKeyInfo {
    return try  FfiConverterTypePgpPublicKeyInfo.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_pgp_key_info(
        FfiConverterData.lower(armoredPublic),$0
    )
})
}
public func recoveryKeyFromPhrase(phrase: String)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_recovery_key_from_phrase(
        FfiConverterString.lower(phrase),$0
    )
})
}
public func sealForRecipient(recipientX25519Pub: Data, recipientMlkemPub: Data, plaintextBody: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_seal_for_recipient(
        FfiConverterData.lower(recipientX25519Pub),
        FfiConverterData.lower(recipientMlkemPub),
        FfiConverterData.lower(plaintextBody),$0
    )
})
}
public func sealMetadataForRecipient(recipientX25519Pub: Data, recipientMlkemPub: Data, metadataJson: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSanctCryptoError.lift) {
    uniffi_sanct_swift_fn_func_seal_metadata_for_recipient(
        FfiConverterData.lower(recipientX25519Pub),
        FfiConverterData.lower(recipientMlkemPub),
        FfiConverterData.lower(metadataJson),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_sanct_swift_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_sanct_swift_checksum_func_compute_subject_hash() != 35707) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_decrypt_bundle_with_recovery() != 23918) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_decrypt_message() != 20661) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_decrypt_metadata() != 31557) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_decrypt_private_keys() != 30519) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_derive_master_key() != 7351) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_encrypt_bundle_for_recovery() != 20514) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_encrypt_draft() != 65467) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_encrypt_message() != 36589) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_encrypt_metadata() != 33576) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_generate_identity_keys() != 10959) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_generate_recovery_phrase() != 6266) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_generate_salt() != 62225) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_hash_recovery_key() != 35138) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_pgp_decrypt_message() != 27534) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_pgp_encrypt_to_recipients() != 47681) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_pgp_export_key() != 17920) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_pgp_generate_key() != 15396) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_pgp_import_key() != 34199) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_pgp_key_info() != 53261) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_recovery_key_from_phrase() != 63661) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_seal_for_recipient() != 64223) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_sanct_swift_checksum_func_seal_metadata_for_recipient() != 27452) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all